### ISSUE TITLE
Fix max 4 accounts limit by export

### ISSUE THREAD

**Issue by uplg** [korki43/gauth-export#4] opened 2022-09-04 02:41 UTC
When uploading an export file (QRCode, limit is at 4 due to a bad QRCode library. Replaced by PR below.)

Fixed by : https://github.com/korki43/gauth-export/pull/3

**Comment by kiehnek** [comment] 2022-09-21 19:41
I'm sorry for taking so long to respond.

I can't reproduce your problem. I can transform my six accounts without a problem using the original library. I'll have a look at your PR in a minute.

**Comment by kiehnek** [comment] 2022-10-07 20:29
I'll close this for now as I cannot reproduce our issue.

**Closed as not planned by kiehnek** 2022-10-07 20:29 UTC

**Comment by uplg** [comment] 2022-10-07 20:31
Ok don't care, I prefer to maintain my own fork ;) (With libs up-to-date and max 4 accounts bug fixed ^^)

**Comment by uplg** [comment] 2022-10-07 20:33
Also, closing an issue because you are not able to reproduce it is not the way, but you know it ;)

**Comment by uplg** [comment] 2022-10-07 20:50
If you have some time sir @korki43 try using a Google Authenticator with 20+ OTP codes, you'll probably find it.

6 may not be sufficient to reproduce.

**Comment by kiehnek** [comment] 2022-10-07 20:55
I tested it with 6 because you said it occurs with more than 4 codes. You have to provide more information for me to understand the problem and why the other library fixed it. 

I have no problem with you maintaining your own fork, but please respect the terms of the MIT license.

**Comment by uplg** [comment] 2022-10-07 20:58
I found your behavior more than cocky, to say the least.

Yep, I said that this occurs for more than 4 codes, because it was like that for me using a Google authenticator with 20+ OTP codes, you asked me for a "dummy qrcode".

So basically, you think that I "imagined" that bug just to make some changes on your code ? That's just not the way to think around it, specially when you are doing "open source".

The fact that you mention "Please respect the terms of the MIT Licence" is a shame actually, I even mentioned you on my fork when I'm not obliged to do so at all. (Just keeping the licence is sufficient with MIT.)

Gn sir. Hopefully you will understand me someday.
